import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import type { SqliteStore } from '../storage/sqlite-store.js';
import { rebuildControlState } from '../control-plane/reducer.js';
import { receiptInputSchema, controlEventSchema, canonicalDigest, redactControlPayload } from '../control-plane/contracts.js';
import { createContextManifest } from '../control-plane/manifest.js';
import { TakeoverManager } from '../control-plane/takeover.js';
import { DomainError } from '../domain/errors.js';
const id=z.string().min(1).max(512).regex(/^[A-Za-z0-9][A-Za-z0-9:._-]*$/);
const empty=z.object({}).strict();
const taskParams=z.object({id}).strict();
const eventSource={kind:'user' as const,sourceId:'threadport',parserVersion:null,coverage:'full' as const};
function controlEvent(input:Partial<z.infer<typeof controlEventSchema>> & Pick<z.infer<typeof controlEventSchema>,'type'|'payload'|'taskId'|'sessionId'|'runId'>):z.infer<typeof controlEventSchema>{return controlEventSchema.parse({eventId:`evt-${randomUUID()}`,protocol:'threadport.control-event.v1',occurredAt:new Date().toISOString(),recordedAt:new Date().toISOString(),source:eventSource,ordinal:null,idempotencyKey:null,evidenceIds:[],...input});}
export function registerControlPlaneRoutes(app:FastifyInstance,store:SqliteStore):void{
 const takeovers=new TakeoverManager();
 app.get('/api/v1/tasks/:id/control',async request=>{empty.parse(request.query);const taskId=taskParams.parse(request.params).id;const cp=store.controlPlane();const events=cp.readAllEvents().filter(event=>event.taskId===taskId);const state=rebuildControlState(events);for(const manifest of cp.listManifests(taskId)){state.manifests[manifest.handoffId]=manifest;for(const receipt of cp.listReceipts(manifest.handoffId))state.receipts[receipt.receiptId]=receipt;}return {data:state};});
 app.get('/api/v1/runs/:id',async request=>{empty.parse(request.query);const runId=taskParams.parse(request.params).id;const events=store.controlPlane().readAllEvents().filter(event=>event.runId===runId);const state=rebuildControlState(events);const session=state.sessions[events[0]?.sessionId ?? runId] ?? {runState:'unknown',health:'coverage-gap',lastEvidenceId:null,lastOccurredAt:null};return {data:{runId,...session}};});
 app.get('/api/v1/handoffs/:id/manifest',async request=>{empty.parse(request.query);const handoffId=taskParams.parse(request.params).id;const manifest=store.controlPlane().getManifest(handoffId);if(!manifest)throw new DomainError('NOT_FOUND','Context manifest does not exist.');return {data:manifest};});
 app.post('/api/v1/handoffs/:id/receipts',async request=>{empty.parse(request.query);const handoffId=taskParams.parse(request.params).id;const body=receiptInputSchema.omit({handoffId:true}).parse(request.body);const cp=store.controlPlane();const manifest=cp.getManifest(handoffId);if(!manifest)throw new DomainError('CONTROL_COVERAGE_GAP','A prepared context manifest is required before accepting a receipt.');if(manifest.digest!==body.manifestDigest)throw new DomainError('RECEIPT_DIGEST_MISMATCH','Receipt manifest digest does not match the prepared manifest.');return {data:cp.saveReceipt({...body,handoffId})};});
 app.post('/api/v1/tasks/:id/control/manifest',async request=>{const taskId=taskParams.parse(request.params).id;const body=z.object({handoffId:id,taskRevision:z.number().int().positive().safe(),targetSessionId:id.optional(),targetRunId:id.optional(),items:z.array(z.object({key:z.string().min(1),text:z.string().nullable().optional(),status:z.enum(['included','summarized','filtered','omitted','unavailable']).optional(),evidenceIds:z.array(id).optional(),reason:z.string().nullable().optional(),readable:z.boolean().optional()}).strict()).max(256).optional(),constraints:z.array(z.object({key:z.string().min(1),text:z.string().nullable().optional(),priority:z.enum(['must','should','may','unknown']).optional(),scope:z.string().optional(),status:z.enum(['included','summarized','filtered','omitted','unavailable']).optional(),evidenceIds:z.array(id).optional(),readable:z.boolean().optional()}).strict()).max(128).optional()}).strict().parse(request.body);const manifest=createContextManifest({handoffId:body.handoffId,taskId,taskRevision:body.taskRevision,targetSessionId:body.targetSessionId,targetRunId:body.targetRunId,items:body.items,constraints:body.constraints});store.controlPlane().saveManifest(manifest);return {data:manifest};});
 app.post('/api/v1/tasks/:id/responsibility/propose',async request=>{const taskId=taskParams.parse(request.params).id;const body=z.object({sessionId:id,scope:z.string().min(1).max(160).default('task'),roles:z.record(id).default({})}).strict().parse(request.body);const event=controlEvent({type:'responsibility.proposed',payload:{id:`responsibility-${randomUUID()}`,taskId,ownerSessionId:body.sessionId,scope:body.scope,roles:body.roles},taskId,sessionId:body.sessionId,runId:null});store.controlPlane().appendEvents([event]);return {data:event};});
 app.post('/api/v1/tasks/:id/responsibility/confirm',async request=>{const taskId=taskParams.parse(request.params).id;const body=z.object({responsibilityId:id,sessionId:id,scope:z.string().min(1).max(160).default('task')}).strict().parse(request.body);const event=controlEvent({type:'responsibility.confirmed',payload:{id:body.responsibilityId,ownerSessionId:body.sessionId,scope:body.scope,roles:{executor:body.sessionId}},taskId,sessionId:body.sessionId,runId:null});store.controlPlane().appendEvents([event]);return {data:event};});
 app.post('/api/v1/runs/:id/takeover',async request=>{const runId=taskParams.parse(request.params).id;const body=z.object({taskId:id,ownerSessionId:id,targetSessionId:id,timeoutMs:z.number().int().positive().max(30000).optional()}).strict().parse(request.body);return {data:await takeovers.request({runId,...body})};});
 app.post('/api/v1/takeovers/:id/acknowledge',async request=>{const takeoverId=taskParams.parse(request.params).id;const body=z.object({successorSessionId:id}).strict().parse(request.body);return {data:takeovers.acknowledge(takeoverId,body.successorSessionId)};});
 app.get('/api/v1/takeovers/:id',async request=>{empty.parse(request.query);const takeoverId=taskParams.parse(request.params).id;return {data:takeovers.get(takeoverId)};});
}
