import { randomUUID } from 'node:crypto';
import type { ControlEvent } from './contracts.js';
const event=(type:string,payload:Record<string,unknown>,patch:Partial<ControlEvent>={}):ControlEvent=>({eventId:`fixture-${randomUUID()}`,protocol:'threadport.control-event.v1',occurredAt:'2026-09-20T00:00:00.000Z',recordedAt:'2026-09-20T00:00:00.000Z',source:{kind:'threadport',sourceId:'fixture',parserVersion:'fixture-v1',coverage:'full'},taskId:'task-fixture',sessionId:'s1',runId:'r1',ordinal:null,type,payload:payload as any,idempotencyKey:null,evidenceIds:[],...patch});
export function normalThreeSessionFixture():ControlEvent[]{return [event('run.started',{},{}),event('lineage.relation',{parentSessionId:'s1',childSessionId:'s2',relation:'handoff',evidenceLevel:'runtime-explicit',status:'confirmed'},{eventId:'fixture-lineage',ordinal:1}),event('run.started',{}, {eventId:'fixture-start-2',sessionId:'s2',runId:'r2',ordinal:2}),event('receipt.confirmed',{receipt:{receiptId:'receipt-1',handoffId:'h1',targetSessionId:'s2',targetRunId:'r2',manifestDigest:'a'.repeat(64),stage:'received',nonce:'fixture-nonce-1234',expiresAt:'2026-09-21T00:00:00.000Z'}},{eventId:'fixture-receipt',sessionId:'s2',runId:'r2',ordinal:3})];}
export function targetNotStartedFixture():ControlEvent[]{return [event('handoff.prepared',{handoffId:'h1'},{}),event('lineage.relation',{parentSessionId:'s1',childSessionId:'s2',relation:'handoff',evidenceLevel:'runtime-explicit',status:'confirmed'},{eventId:'fixture-target-not-started',ordinal:1})];}
export function lateDuplicateFixture():ControlEvent[]{const first=event('run.started',{}, {eventId:'fixture-duplicate',ordinal:2});return [first,{...first,ordinal:1},{...first}];}
export function changedFileFixture():ControlEvent[]{return [event('manifest.saved',{handoffId:'h1',manifest:{protocol:'threadport.context-manifest.v1',handoffId:'h1',taskId:'task-fixture',taskRevision:1,createdAt:'2026-09-20T00:00:00.000Z',digest:'a'.repeat(64),items:[],constraints:[]}}),event('attention.opened',{kind:'manifest-drift',severity:'error',message:'Prepared context changed before receipt.'},{eventId:'fixture-drift',ordinal:1})];}
export function abandonedChildFixture():ControlEvent[]{return [event('lineage.relation',{parentSessionId:'s1',childSessionId:'s2',relation:'fork',evidenceLevel:'inferred',status:'candidate'}),event('attention.opened',{kind:'orphan-child',severity:'warning',message:'Child session has no confirmed owner.'},{eventId:'fixture-orphan',ordinal:1})];}
export function stopUnavailableFixture():ControlEvent[]{return [event('attention.opened',{kind:'stop-unavailable',severity:'warning',message:'No reliable stop control is available.'})];}
export function forgedReceiptFixture():ControlEvent[]{return [event('receipt.confirmed',{receipt:{receiptId:'receipt-forged',handoffId:'h1',targetSessionId:'wrong',targetRunId:'wrong',manifestDigest:'b'.repeat(64),stage:'verified-complete',nonce:'forged-nonce-1234',expiresAt:'2026-09-21T00:00:00.000Z'}},{source:{kind:'agent-report',sourceId:'fixture',parserVersion:'fixture-v1',coverage:'partial'}})];}
export const controlPlaneFixtures={normalThreeSession:normalThreeSessionFixture,targetNotStarted:targetNotStartedFixture,lateDuplicate:lateDuplicateFixture,changedFile:changedFileFixture,abandonedChild:abandonedChildFixture,stopUnavailable:stopUnavailableFixture,forgedReceipt:forgedReceiptFixture};

