import { pathToFileURL } from 'node:url';
import { resolve,join } from 'node:path';
import { mkdtemp,writeFile,readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
const root=resolve(process.argv[2]);
const {tracesFromEvents,assembleCapsule}=await import(pathToFileURL(join(root,'dist/src/adapters/common.js')));
const {gitStateMatches,readGitState}=await import(pathToFileURL(join(root,'dist/src/git.js')));
const {runCli}=await import(pathToFileURL(join(root,'dist/src/cli.js')));
const repo=await mkdtemp(join(tmpdir(),'threadport-audit-'));
for(const args of [['init','-b','main'],['config','user.name','Audit'],['config','user.email','audit@example.invalid']])execFileSync('git',['-C',repo,...args]);
await writeFile(join(repo,'README.md'),'audit fixture\n');execFileSync('git',['-C',repo,'add','.']);execFileSync('git',['-C',repo,'commit','-m','fixture']);
const ev=[{type:'user',text:'Implement A.'},{type:'assistant',text:'I will use SQLite.'},{type:'user',text:'Change the objective to B.\n不要修改数据库。'},{type:'command',command:'npm test',exitCode:1},{type:'command',command:'npm test',exitCode:0},{type:'command',command:'npm test',exitCode:1},{type:'command',command:'pnpm test',exitCode:0}];
const trace=tracesFromEvents(ev);
const capsule=await assembleCapsule({agent:'cursor',sessionId:'audit',traces:{...trace,files:new Map([['a',{path:join(repo,'src/a/index.ts'),action:'modified'}],['b',{path:join(repo,'src/b/index.ts'),action:'modified'}]])},input:{project:{name:'audit',root:repo}},evidenceTitle:'Synthetic audit fixture'});
const immediateGitMatch=gitStateMatches(capsule.git,await readGitState(repo));
await writeFile(join(repo,'capsule.json'),JSON.stringify(capsule));
let output='';let errors='';const io={cwd:()=>repo,stdout:{write:s=>output+=s},stderr:{write:s=>errors+=s}};
const validation=await runCli(['validate','capsule.json'],io);
const result={immediateGitMatch,objective:trace.objective,constraints:trace.constraints,decisions:trace.decisions,status:trace.status,failures:trace.failures,tests:trace.tests,portableFiles:capsule.files,gitMatchWithCurrent:gitStateMatches(capsule.git,await readGitState(repo)),validateExit:validation,validateOutput:output,notes:'Synthetic probes; no real user sessions or secrets accessed.'};
console.log(JSON.stringify(result,null,2));
