import { afterEach, describe, expect, it } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises'; import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { openStore } from '../../src/storage/sqlite-store.js'; import { createContextManifest } from '../../src/control-plane/manifest.js'; import type { ControlEvent } from '../../src/control-plane/contracts.js';
const dirs:string[]=[]; afterEach(async()=>{for(const d of dirs.splice(0)) await rm(d,{recursive:true,force:true});});
const ev=(id:string, body:Partial<ControlEvent>={}):ControlEvent=>({eventId:id,protocol:'threadport.control-event.v1',occurredAt:null,recordedAt:'2026-09-20T00:00:00.000Z',source:{kind:'threadport',sourceId:'tp',parserVersion:'1',coverage:'full'},taskId:null,sessionId:'s',runId:'r',ordinal:null,type:'run.started',payload:{},idempotencyKey:null,evidenceIds:[id],...body});
describe('control plane storage',()=>{
 it('appends idempotent events and exposes conflicts',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();expect(cp.appendEvents([ev('e1')])).toEqual({inserted:['e1'],duplicate:[]});expect(cp.appendEvents([ev('e1')])).toEqual({inserted:[],duplicate:['e1']});expect(()=>cp.appendEvents([ev('e1',{payload:{reason:'different'}})] )).toThrowError(expect.objectContaining({code:'REVISION_CONFLICT'}));expect(cp.readEvents()).toHaveLength(1);}finally{store.close();}});
 it('treats equivalent payload key order as an idempotent replay',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();const first=ev('e-order',{payload:{reason:'same',exitCode:0}});const replay=ev('e-order',{payload:{exitCode:0,reason:'same'}});expect(cp.appendEvents([first])).toEqual({inserted:['e-order'],duplicate:[]});expect(cp.appendEvents([replay])).toEqual({inserted:[],duplicate:['e-order']});}finally{store.close();}});
 it('keeps manifests immutable, retries identical receipts, and records expiry',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();const manifest=createContextManifest({handoffId:'h1',taskId:'t1',taskRevision:1,targetSessionId:'s2',targetRunId:'r2',createdAt:'2026-09-20T00:00:00.000Z'});cp.saveManifest(manifest);expect(cp.getManifest('h1')).toEqual(manifest);expect(()=>cp.saveManifest({...manifest,digest:'b'.repeat(64)})).toThrowError(expect.objectContaining({code:'RECEIPT_DIGEST_MISMATCH'}));const input={handoffId:'h1',targetSessionId:'s2',targetRunId:'r2',manifestDigest:manifest.digest,stage:'received' as const,nonce:'nonce-1234567890',expiresAt:'2026-09-21T00:00:00.000Z'};const a=cp.saveReceipt(input);const b=cp.saveReceipt(input);expect(a.status).toBe('expired');expect(b).toEqual(a);expect(cp.listReceipts('h1')).toHaveLength(1);}finally{store.close();}});
 it('uses a stable nonce conflict error for conflicting retries',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();const manifest=createContextManifest({handoffId:'h2',taskId:'t1',taskRevision:1,targetSessionId:'s2',targetRunId:'r2',createdAt:'2026-09-20T00:00:00.000Z'});cp.saveManifest(manifest);const base={handoffId:'h2',targetSessionId:'s2',targetRunId:'r2',manifestDigest:manifest.digest,stage:'received' as const,nonce:'nonce-1234567890',expiresAt:'2026-09-21T00:00:00.000Z'};cp.saveReceipt(base);expect(()=>cp.saveReceipt({...base,targetRunId:'r3'})).toThrowError(expect.objectContaining({code:'RECEIPT_NONCE_CONFLICT'}));}finally{store.close();}});
 it('rejects a receipt for a target different from the prepared manifest',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();const manifest=createContextManifest({handoffId:'h3',taskId:'t1',taskRevision:1,targetSessionId:'s2',targetRunId:'r2',createdAt:'2026-09-20T00:00:00.000Z'});cp.saveManifest(manifest);expect(()=>cp.saveReceipt({handoffId:'h3',targetSessionId:'s3',targetRunId:'r3',manifestDigest:manifest.digest,stage:'received',nonce:'nonce-1234567890',expiresAt:'2026-09-21T00:00:00.000Z'})).toThrowError(expect.objectContaining({code:'RECEIPT_TARGET_MISMATCH'}));}finally{store.close();}});
 it('rejects a receipt when the manifest has no prepared target',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();const manifest=createContextManifest({handoffId:'h4',taskId:'t1',taskRevision:1,createdAt:'2026-09-20T00:00:00.000Z'});cp.saveManifest(manifest);expect(()=>cp.saveReceipt({handoffId:'h4',targetSessionId:'arbitrary-session',targetRunId:'arbitrary-run',manifestDigest:manifest.digest,stage:'received',nonce:'nonce-1234567890',expiresAt:'2026-09-21T00:00:00.000Z'})).toThrowError(expect.objectContaining({code:'RECEIPT_TARGET_MISMATCH'}));}finally{store.close();}});
 it('rejects a direct verified-complete receipt write',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();const manifest=createContextManifest({handoffId:'h5',taskId:'t1',taskRevision:1,targetSessionId:'s2',targetRunId:'r2',createdAt:'2026-09-20T00:00:00.000Z'});cp.saveManifest(manifest);expect(()=>cp.saveReceipt({handoffId:'h5',targetSessionId:'s2',targetRunId:'r2',manifestDigest:manifest.digest,stage:'verified-complete',nonce:'nonce-1234567890',expiresAt:'2026-09-21T00:00:00.000Z'})).toThrowError(expect.objectContaining({code:'RECEIPT_VERIFICATION_REQUIRED'}));}finally{store.close();}});
 it('replays all events beyond one page',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();const events=Array.from({length:1001},(_,i)=>ev(`page-${i}`,{ordinal:i,taskId:'task-page'}));expect(cp.appendEvents(events)).toMatchObject({inserted:expect.arrayContaining(['page-1000'])});expect(cp.readAllEvents()).toHaveLength(1001);}finally{store.close();}});
 it('rejects malformed responsibility and observation records',async()=>{const d=await mkdtemp(join(tmpdir(),'tp-cp-'));dirs.push(d);const store=await openStore({dataDir:d});try{const cp=store.controlPlane();expect(()=>cp.saveResponsibility({id:'r',taskId:'t',scope:'task',roles:{executor:'C:\\secret'},status:'confirmed',evidenceIds:[],confirmedAt:null})).toThrowError(expect.objectContaining({code:'INVALID_INPUT'}));expect(()=>cp.saveRunObservation({observationId:'o',runId:'r',sessionId:null,runState:'not-a-state' as never,health:'current',observedAt:null,evidenceId:null})).toThrowError(expect.objectContaining({code:'INVALID_INPUT'}));}finally{store.close();}});
});
