CREATE TABLE search_state(id INTEGER PRIMARY KEY CHECK(id=1), generation INTEGER NOT NULL CHECK(generation>=0));
INSERT INTO search_state VALUES(1,0);
CREATE TRIGGER search_sources_insert AFTER INSERT ON sources BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_sources_update AFTER UPDATE ON sources WHEN OLD.id IS NOT NEW.id OR OLD.agent IS NOT NEW.agent BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_sources_delete AFTER DELETE ON sources BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_projects_insert AFTER INSERT ON projects BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_projects_update AFTER UPDATE ON projects WHEN OLD.id IS NOT NEW.id OR OLD.name IS NOT NEW.name BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_projects_delete AFTER DELETE ON projects BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_workspaces_insert AFTER INSERT ON workspaces BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_workspaces_update AFTER UPDATE ON workspaces WHEN OLD.id IS NOT NEW.id OR OLD.project_id IS NOT NEW.project_id OR OLD.canonical_root IS NOT NEW.canonical_root BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_workspaces_delete AFTER DELETE ON workspaces BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_sessions_insert AFTER INSERT ON sessions BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_sessions_update AFTER UPDATE ON sessions WHEN OLD.id IS NOT NEW.id OR OLD.source_id IS NOT NEW.source_id OR OLD.project_id IS NOT NEW.project_id OR OLD.workspace_id IS NOT NEW.workspace_id OR OLD.last_event_at IS NOT NEW.last_event_at OR json_extract(OLD.metadata_json,'$.session.agent') IS NOT json_extract(NEW.metadata_json,'$.session.agent') BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_sessions_delete AFTER DELETE ON sessions BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_events_insert AFTER INSERT ON events BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_events_update AFTER UPDATE ON events WHEN OLD.id IS NOT NEW.id OR OLD.session_id IS NOT NEW.session_id OR OLD.ordinal IS NOT NEW.ordinal OR OLD.search_text IS NOT NEW.search_text BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_events_delete AFTER DELETE ON events BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_tasks_insert AFTER INSERT ON tasks BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_tasks_update AFTER UPDATE ON tasks WHEN OLD.id IS NOT NEW.id OR OLD.project_id IS NOT NEW.project_id OR OLD.body_json IS NOT NEW.body_json BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_tasks_delete AFTER DELETE ON tasks BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_task_sessions_insert AFTER INSERT ON task_sessions BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_task_sessions_update AFTER UPDATE ON task_sessions WHEN OLD.session_id IS NOT NEW.session_id OR OLD.task_id IS NOT NEW.task_id BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
CREATE TRIGGER search_task_sessions_delete AFTER DELETE ON task_sessions BEGIN UPDATE search_state SET generation=generation+1 WHERE id=1; END;
